Internal Server Error: /neunet/upload_image/
Traceback (most recent call last):
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\Documents\ParkEasy\ParkEasy\neural_networks\views.py", line 12, in upload_car_image
    path_to_number_plate = get_number_in_text(image_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\Documents\ParkEasy\ParkEasy\neural_networks\implement_model_ocr.py", line 141, in get_number_in_text
    return extract_license_plate_text("neural_networks/test_images/ocr/output_img.jpg")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\Documents\ParkEasy\ParkEasy\neural_networks\implement_model_ocr.py", line 32, in extract_license_plate_text
    for word_info in line:
TypeError: 'NoneType' object is not iterable
Internal Server Error: /neunet/upload_image/
Traceback (most recent call last):
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\inference_sdk\http\client.py", line 83, in decorate
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\inference_sdk\http\client.py", line 241, in infer
    return self.infer_from_api_v0(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\inference_sdk\http\client.py", line 303, in infer_from_api_v0
    responses = execute_requests_packages(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\inference_sdk\http\utils\executors.py", line 48, in execute_requests_packages
    api_key_safe_raise_for_status(response=response)
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\inference_sdk\http\utils\requests.py", line 16, in api_key_safe_raise_for_status
    response.raise_for_status()
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://detect.roboflow.com/license-plates-us-eu-1tufg/1?api_key=9c***5Z&disable_active_learning=False

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\Documents\ParkEasy\ParkEasy\neural_networks\views.py", line 12, in upload_car_image
    path_to_number_plate = get_number_in_text(image_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\Documents\ParkEasy\ParkEasy\neural_networks\implement_model_ocr.py", line 136, in get_number_in_text
    plate_path = get_plate_number_image(source_image_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\Documents\ParkEasy\ParkEasy\neural_networks\implement_model_detect.py", line 18, in get_plate_number_image
    model_predict = CLIENT.infer(resize_image_path, model_id="license-plates-us-eu-1tufg/1")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RollPy\AppData\Local\pypoetry\Cache\virtualenvs\parkeasy-NmE8ZzPf-py3.11\Lib\site-packages\inference_sdk\http\client.py", line 93, in decorate
    raise HTTPCallErrorError(
inference_sdk.http.errors.HTTPCallErrorError: HTTPCallErrorError(description='403 Client Error: Forbidden for url: https://detect.roboflow.com/license-plates-us-eu-1tufg/1?api_key=9c***5Z&disable_active_learning=False', api_message='Forbidden',status_code=403)
